load("//theorem:defs.bzl", "theorem")

theorem(
    name = "irreflexive",
    srcs = ["irreflexive.wave"],
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

theorem(
    name = "transitive",
    srcs = ["transitive.wave"],
    configuration = 8192,
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

theorem(
    name = "trichotomy",
    srcs = ["trichotomy.wave"],
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
