load("//theorem:defs.bzl", "theorem")

exports_files(
    [
        "converse.wave",
        "order.wave",
    ],
    visibility = ["//book:__pkg__"],
)

theorem(
    name = "antisymmetry",
    srcs = ["antisymmetry.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "complement",
    srcs = ["complement.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "converse",
    srcs = ["converse.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "distributivity",
    srcs = ["distributivity.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "idempotence",
    srcs = ["idempotence.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "modularity",
    srcs = ["modularity.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "order",
    srcs = ["order.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "transitivity",
    srcs = ["transitivity.wave"],
    path = False,
    deps = [],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
