load("//photonic:defs.bzl", "photonic_binary", "photonic_test")

photonic_binary(
    name = "pipeline",
    srcs = ["pipeline.wave"],
    visibility = ["//photonic:__pkg__"],
    deps = [
        "//library/boolean:and",
        "//library/boolean:not",
        "//library/collection:copy",
        "//library/collection:map",
        "//library/collection:reduce",
    ],
)

photonic_test(
    name = "pipeline.check",
    srcs = ["pipeline.wave"],
    path = True,
    preserve = True,
    targets = ["First.False, Second.True"],
    deps = [
        "//library/boolean:and",
        "//library/boolean:not",
        "//library/collection:copy",
        "//library/collection:map",
        "//library/collection:reduce",
    ],
)

filegroup(
    name = "fixture",
    srcs = [
        "pipeline.particle",
        "pipeline.wave",
    ],
    visibility = ["//library:__pkg__"],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)

photonic_test(
    name = "function.reject",
    srcs = ["function.wave"],
    expect = "unreachable",
    preserve = True,
    targets = [
        """Left.Grove.([First.Seed] Return.Bud).([Second.Bud] Return.Flower),
Right.Grove.([First.Seed] (
    Function.Compose.Sapling.([First.Sapling] Return.Trunk).([Second.Trunk] Return.Tree)
    [Return] Return
)).([Second.Tree] Return.Grove).([First.Sapling] Return.Trunk).([Second.Trunk] Return.Tree)
""",
        """Left.Flower.([First.Seed] Return.Bud).([Second.Bud] Return.Flower),
Right.Flower.([First.Seed] (
    Function.Compose.Sapling.([First.Sapling] Return.Trunk).([Second.Trunk] Return.Tree)
    [Return] Return
)).([Second.Tree] Return.Grove).([First.Sapling] Return.Trunk).([Second.Trunk] Return.Tree)
""",
    ],
    deps = ["//library/function:compose"],
)

photonic_binary(
    name = "function",
    srcs = ["function.wave"],
    deps = ["//library/function:compose"],
)

photonic_test(
    name = "function.check",
    srcs = ["function.wave"],
    preserve = True,
    targets = ["""Left.Flower.([First.Seed] Return.Bud).([Second.Bud] Return.Flower),
Right.Grove.([First.Seed] (
    Function.Compose.Sapling.([First.Sapling] Return.Trunk).([Second.Trunk] Return.Tree)
    [Return] Return
)).([Second.Tree] Return.Grove).([First.Sapling] Return.Trunk).([Second.Trunk] Return.Tree)
"""],
    deps = ["//library/function:compose"],
)
