load("//photonic:defs.bzl", "photonic_library")

exports_files(
    ["case.particle"],
    visibility = ["//book:__pkg__"],
)

photonic_library(
    name = "case",
    srcs = ["case.particle"],
    visibility = [
        "//theorem/boolean:__pkg__",
        "//theorem/carry:__pkg__",
        "//theorem/coloring:__pkg__",
        "//theorem/componentwise:__pkg__",
        "//theorem/counting:__pkg__",
        "//theorem/induction:__pkg__",
        "//theorem/lexicographic:__pkg__",
        "//theorem/natural:__pkg__",
        "//theorem/relation:__pkg__",
        "//theorem/sequence:__pkg__",
        "//theorem/sum:__pkg__",
        "//theorem/ternary:__pkg__",
    ],
)

photonic_library(
    name = "cover",
    srcs = ["cover.particle"],
    visibility = [
        "//theorem/componentwise:__pkg__",
        "//theorem/lexicographic:__pkg__",
        "//theorem/relation:__pkg__",
        "//theorem/sum:__pkg__",
    ],
)

photonic_library(
    name = "judge",
    srcs = ["judge.particle"],
    visibility = [
        "//theorem/sequence:__pkg__",
        "//theorem/ternary:__pkg__",
    ],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
        "defs.bzl",
    ],
    visibility = ["//:__pkg__"],
)
