load("@default_rust_toolchains//rustc:component_labels.bzl", "rust_toolchain_component_label")
load("@hermetic_launcher//launcher:launcher_binary.bzl", "launcher_binary")

launcher_binary(
    name = "format",
    embedded_args = [
        "system/photonic.rs",
        "system/test.rs",
        "system/command.rs",
        "system/benchmark.rs",
        "system/benchmark/symmetry.rs",
        "mathematics/natural/record.rs",
    ],
    entrypoint = rust_toolchain_component_label("@rules_rust//tools/upstream_wrapper:rustfmt"),
    tags = ["manual"],
)

launcher_binary(
    name = "update",
    embedded_args = ["update"],
    entrypoint = rust_toolchain_component_label("@rules_rust//tools/upstream_wrapper:cargo"),
    tags = ["manual"],
)

exports_files(glob(["example/*.wave", "example/*.json"]))
