load("@crate//:defs.bzl", "lint_config")
load("@default_rust_toolchains//rustc:component_labels.bzl", "rust_toolchain_component_label")
load("//toolchain:defs.bzl", "hermetic_binary")

hermetic_binary(
    name = "analyze.rust",
    entrypoint = "@rules_rs//tools/rust_analyzer:gen_rust_project",
    tags = ["manual"],
)

hermetic_binary(
    name = "format",
    argument = [
        "$(rlocationpath {})".format(rust_toolchain_component_label("@rules_rust//tools/upstream_wrapper:rustfmt")),
    ],
    data = [rust_toolchain_component_label("@rules_rust//tools/upstream_wrapper:rustfmt")],
    entrypoint = "//toolchain:format",
    tags = ["manual"],
)

hermetic_binary(
    name = "link",
    argument = [
        "README.md",
        "index.html",
    ],
    entrypoint = "//toolchain:link",
    tags = ["manual"],
)

hermetic_binary(
    name = "update",
    argument = [
        "$(rlocationpath {})".format(rust_toolchain_component_label("@rules_rust//tools/upstream_wrapper:cargo")),
        "--",
        "update",
    ],
    data = [rust_toolchain_component_label("@rules_rust//tools/upstream_wrapper:cargo")],
    entrypoint = "//toolchain:execute",
    tags = ["manual"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
        "MODULE.bazel",
        "//arithmetic:build",
        "//benchmark:build",
        "//book:build",
        "//code:build",
        "//command:build",
        "//frontend:build",
        "//gpu:build",
        "//language:build",
        "//learning:build",
        "//library:build",
        "//library/binary:build",
        "//library/boolean:build",
        "//library/carry:build",
        "//library/chain:build",
        "//library/collection:build",
        "//library/expression:build",
        "//library/field:build",
        "//library/function:build",
        "//library/integer:build",
        "//library/natural:build",
        "//library/selection:build",
        "//library/stream:build",
        "//library/ternary:build",
        "//library/vector:build",
        "//machine:build",
        "//network:build",
        "//photonic:build",
        "//platform:build",
        "//program/association:build",
        "//program/binary:build",
        "//program/circuit:build",
        "//program/composition:build",
        "//program/decimal:build",
        "//program/language:build",
        "//program/natural:build",
        "//program/ternary:build",
        "//program/ternary/case:build",
        "//program/vector:build",
        "//random:build",
        "//theorem:build",
        "//theorem/boolean:build",
        "//theorem/carry:build",
        "//theorem/chain:build",
        "//theorem/coloring:build",
        "//theorem/componentwise:build",
        "//theorem/counting:build",
        "//theorem/group:build",
        "//theorem/induction:build",
        "//theorem/lattice:build",
        "//theorem/lexicographic:build",
        "//theorem/monoid:build",
        "//theorem/natural:build",
        "//theorem/relation:build",
        "//theorem/ring:build",
        "//theorem/sequence:build",
        "//theorem/sum:build",
        "//theorem/ternary:build",
        "//toolchain:build",
        "//toolchain/browser:build",
        "//toolchain/wasm:build",
        "//translation:build",
    ],
    visibility = ["//toolchain:__pkg__"],
)

filegroup(
    name = "page",
    srcs = ["index.html"],
    visibility = [
        "//book:__pkg__",
        "//toolchain/browser:__pkg__",
    ],
)

filegroup(
    name = "lightbox",
    srcs = ["lightbox.html"],
    visibility = [
        "//book:__pkg__",
        "//toolchain/browser:__pkg__",
    ],
)

alias(
    name = "lint",
    actual = lint_config(),
    visibility = [
        "//arithmetic:__pkg__",
        "//benchmark:__pkg__",
        "//code:__pkg__",
        "//command:__pkg__",
        "//frontend:__pkg__",
        "//gpu:__pkg__",
        "//language:__pkg__",
        "//learning:__pkg__",
        "//library:__pkg__",
        "//machine:__pkg__",
        "//network:__pkg__",
        "//photonic:__pkg__",
        "//program/binary:__pkg__",
        "//random:__pkg__",
        "//toolchain:__pkg__",
        "//toolchain/browser:__pkg__",
        "//translation:__pkg__",
    ],
)
