module(
    name = "photonic",
    version = "0.0.0",
    bazel_compatibility = [">=9.2.0"],
)

bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.4", dev_dependency = True)

bazel_dep(name = "hermetic_launcher", version = "0.0.15")
bazel_dep(name = "llvm", version = "0.8.19")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_rs", version = "0.0.110")
single_version_override(
    module_name = "rules_rs",
    patch_strip = 1,
    patches = ["//platform:rust.patch"],
)

toolchain = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains")

determinism = {
    target: ["-Clink-arg=-Wl,--no-insert-timestamp"]
    for target in [
        "aarch64-pc-windows-gnullvm",
        "x86_64-pc-windows-gnullvm",
    ]
}

toolchain.toolchain(
    edition = "2024",
    extra_exec_rustc_flags = determinism,
    extra_rustc_flags = determinism,
    use_rust_redist = False,
    version = "1.98.1",
)
use_repo(toolchain, "default_rust_toolchains")

register_toolchains(
    "@default_rust_toolchains//...",
    "@llvm//toolchain:all",
)

crate = use_extension("@rules_rs//rs:extensions.bzl", "crate")
crate.from_cargo(
    name = "crate",
    cargo_lock = "//:Cargo.lock",
    cargo_toml = "//:Cargo.toml",
    platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-pc-windows-gnullvm",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-pc-windows-gnullvm",
        "x86_64-unknown-linux-gnu",
    ],
)
use_repo(crate, "crate")

rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust")
use_repo(rust, "rules_rust")

bazel_dep(name = "rules_browsers", version = "0.4.0", dev_dependency = True)
bazel_dep(name = "rules_nodejs", version = "6.7.5", dev_dependency = True)

bazel_dep(name = "bazel_skylib", version = "1.9.0")

bazel_dep(name = "aspect_bazel_lib", version = "2.22.5", dev_dependency = True)

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node", dev_dependency = True)
node.toolchain(node_version = "22.18.0")
use_repo(node, "nodejs_toolchains")

browser = use_extension("@rules_browsers//browsers:extensions.bzl", "browsers", dev_dependency = True)
browser.chrome(version = "147.0.7687.0")
browser.chromedriver(version = "147.0.7687.0")
use_repo(browser, "rules_browsers_chrome_mac_arm", "rules_browsers_chromedriver_mac_arm")
