load("//photonic:defs.bzl", "photonic_library")
load("//theorem:defs.bzl", "refutation", "theorem")

theorem(
    name = "pigeonhole.four",
    srcs = ["pigeonhole.four.wave"],
    deps = [
        "//library/boolean:or",
        "//library/ternary:equal",
        "//theorem:case",
    ],
)

refutation(
    name = "pigeonhole.three",
    srcs = ["pigeonhole.three.wave"],
    outcome = "Counterexample.([P] 0).([Q] 1).([R] 2)",
    deps = [
        "//library/boolean:or",
        "//library/ternary:equal",
        "//theorem:case",
    ],
)

theorem(
    name = "progression.nine",
    srcs = ["progression.nine.wave"],
    configuration = 65536,
    occurrence = 512,
    deps = [
        ":uniform",
        "//library/boolean:or",
        "//theorem:case",
    ],
)

refutation(
    name = "progression.eight",
    srcs = ["progression.eight.wave"],
    configuration = 8192,
    occurrence = 512,
    outcome = "Counterexample.([One] True).([Two] True).([Three] False).([Four] False).([Five] True).([Six] True).([Seven] False).([Eight] False)",
    deps = [
        ":uniform",
        "//library/boolean:or",
        "//theorem:case",
    ],
)

theorem(
    name = "sum.five",
    srcs = ["sum.five.wave"],
    deps = [
        ":uniform",
        "//library/boolean:or",
        "//theorem:case",
    ],
)

refutation(
    name = "sum.four",
    srcs = ["sum.four.wave"],
    outcome = "Counterexample.([One] True).([Two] False).([Three] False).([Four] True)",
    deps = [
        ":uniform",
        "//library/boolean:or",
        "//theorem:case",
    ],
)

theorem(
    name = "triangle.six",
    srcs = ["triangle.six.wave"],
    configuration = 16384,
    occurrence = 512,
    deps = [
        ":uniform",
        "//library/boolean:or",
        "//theorem:case",
    ],
)

refutation(
    name = "triangle.five",
    srcs = ["triangle.five.wave"],
    outcome = "Counterexample.([[Edge] A.B] True).([[Edge] A.C] True).([[Edge] A.D] False).([[Edge] A.E] False).([[Edge] B.C] False).([[Edge] B.D] True).([[Edge] B.E] False).([[Edge] C.D] False).([[Edge] C.E] True).([[Edge] D.E] True)",
    deps = [
        ":uniform",
        "//library/boolean:or",
        "//theorem:case",
    ],
)

photonic_library(
    name = "uniform",
    srcs = ["uniform.particle"],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
