agents:
  queue: linux-small

steps:
  - label: Build · Linux x86-64
    key: build
    command:
      - bazel build --config=ci //...
      - bazel run --config=ci //:format -- --check
      - bazel run --config=ci //:update -- --help
    timeout_in_minutes: 60
    notify:
      - github_commit_status:
          context: Build · Linux x86-64

  - label: Test · Linux x86-64
    key: test
    command: bazel test --config=ci --config=continuous //...
    timeout_in_minutes: 60
    notify:
      - github_commit_status:
          context: Test · Linux x86-64
