load("//photonic:defs.bzl", "photonic_test")

photonic_test(
    name = "precedence",
    srcs = ["precedence.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "association",
    srcs = ["association.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "borrow",
    srcs = ["borrow.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "product",
    srcs = ["product.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "remainder",
    srcs = ["remainder.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "equal",
    srcs = ["equal.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "empty",
    srcs = ["empty.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "leading",
    srcs = ["leading.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "short",
    srcs = ["short.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "depth",
    srcs = ["depth.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "width",
    srcs = ["width.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    tags = ["memory"],
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "divisor",
    srcs = ["divisor.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Evaluate.Error.Divisor"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "opening",
    srcs = ["opening.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Evaluate.Error.Syntax"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "closing",
    srcs = ["closing.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Evaluate.Error.Syntax"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "trailing",
    srcs = ["trailing.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Evaluate.Error.Syntax"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "consecutive",
    srcs = ["consecutive.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Evaluate.Error.Syntax"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "missing",
    srcs = ["missing.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Evaluate.Error.Syntax"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "stack",
    srcs = ["stack.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Execute.Error.Stack"],
    work = 100000000,
    deps = ["//library/expression:execute"],
)

photonic_test(
    name = "extra",
    srcs = ["extra.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Execute.Error.Stack"],
    work = 100000000,
    deps = ["//library/expression:execute"],
)

photonic_test(
    name = "operand",
    srcs = ["operand.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Return.Expression.Execute.Error.Stack"],
    work = 100000000,
    deps = ["//library/expression:execute"],
)

photonic_test(
    name = "negative",
    srcs = ["negative.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "unary",
    srcs = ["unary.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "difference",
    srcs = ["difference.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "sign",
    srcs = ["sign.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "quotient",
    srcs = ["quotient.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "double",
    srcs = ["double.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "cancel",
    srcs = ["cancel.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.0",
    srcs = ["polarity.0.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.1",
    srcs = ["polarity.1.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.2",
    srcs = ["polarity.2.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.3",
    srcs = ["polarity.3.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.4",
    srcs = ["polarity.4.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.5",
    srcs = ["polarity.5.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.6",
    srcs = ["polarity.6.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.7",
    srcs = ["polarity.7.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.8",
    srcs = ["polarity.8.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.9",
    srcs = ["polarity.9.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.10",
    srcs = ["polarity.10.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.11",
    srcs = ["polarity.11.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.12",
    srcs = ["polarity.12.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.13",
    srcs = ["polarity.13.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.14",
    srcs = ["polarity.14.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "polarity.15",
    srcs = ["polarity.15.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "complement",
    srcs = ["complement.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "padding",
    srcs = ["padding.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "opposite",
    srcs = ["opposite.wave"],
    coherence = 1024,
    configuration = 65536,
    occurrence = 16384,
    path = True,
    preserve = True,
    record = 100000000,
    scope = 2048,
    target = ["Done.Zero"],
    work = 100000000,
    deps = ["//library/expression:evaluate"],
)

photonic_test(
    name = "repeated",
    srcs = ["repeated.wave"],
    coherence = 512,
    configuration = 32768,
    occurrence = 8192,
    path = True,
    preserve = True,
    record = 2000000,
    scope = 1024,
    tags = ["memory"],
    target = ["Done.Zero"],
    work = 1000000,
    deps = ["//library/expression:evaluate"],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
