load("//photonic:defs.bzl", "photonic_library")
load("//theorem:defs.bzl", "theorem")

photonic_library(
    name = "role",
    srcs = ["role.particle"],
    visibility = ["//theorem/induction:__pkg__"],
)

theorem(
    name = "action",
    srcs = ["action.wave"],
    deps = [
        ":role",
        "//library/carry:combine",
        "//library/carry:evaluate",
        "//library/ternary:equal",
        "//theorem:case",
    ],
)

theorem(
    name = "associativity",
    srcs = ["associativity.wave"],
    occurrence = 512,
    deps = [
        ":role",
        "//library/carry:combine",
        "//library/carry:equal",
        "//theorem:case",
    ],
)

theorem(
    name = "identity",
    srcs = ["identity.wave"],
    deps = [
        ":role",
        "//library/carry:combine",
        "//library/carry:equal",
        "//theorem:case",
    ],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
