load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_binary(
    name = "assemble",
    srcs = ["assemble.rs"],
    crate_root = "assemble.rs",
    lint_config = "//:lint",
    deps = [
        "//frontend",
        "@crate//:clap",
        "@crate//:miette",
        "@crate//:serde_json",
    ],
)

rust_binary(
    name = "launch",
    srcs = ["launch.rs"],
    crate_root = "launch.rs",
    lint_config = "//:lint",
    visibility = [
        "//program:__subpackages__",
        "//theorem:__subpackages__",
    ],
    deps = [
        "//toolchain:relay",
        "@rules_rust//rust/runfiles",
    ],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
        "defs.bzl",
    ],
    visibility = ["//:__pkg__"],
)

rust_test(
    name = "test",
    srcs = ["test.rs"],
    crate_root = "test.rs",
    data = [
        ":assemble",
        ":check",
        ":launch",
        "//command:photonic",
        "//program/composition:pipeline.program",
        "//program/ternary:local",
        "//program/ternary:local.program",
    ],
    env = {
        "CHECK": "$(rlocationpath :check)",
        "ASSEMBLE": "$(rlocationpath :assemble)",
        "LAUNCH": "$(rlocationpath :launch)",
        "LOCAL": "$(rlocationpath //program/ternary:local)",
        "BUNDLE": "$(rlocationpath //program/ternary:local.program)",
        "COMMAND": "$(rlocationpath //command:photonic)",
        "PIPELINE": "$(rlocationpath //program/composition:pipeline.program)",
    },
    lint_config = "//:lint",
    deps = [
        "//frontend",
        "//language:photonic",
        "@crate//:serde_json",
        "@rules_rust//rust/runfiles",
    ],
)

rust_binary(
    name = "check",
    srcs = ["check.rs"],
    crate_root = "check.rs",
    lint_config = "//:lint",
    visibility = [
        "//library:__subpackages__",
        "//program:__subpackages__",
        "//theorem:__subpackages__",
    ],
    deps = [
        "//frontend",
        "//language:photonic",
        "@crate//:miette",
        "@crate//:serde",
        "@crate//:serde_json",
        "@rules_rust//rust/runfiles",
    ],
)
