load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_test(
    name = "test",
    size = "small",
    srcs = glob(["*.rs"]),
    crate_root = "test.rs",
    compile_data = [
        "//:example/conjunction.lava",
        "//:example/reference.json",
        "//:mathematics/natural/addition.lava",
        "//:mathematics/natural/result.lava",
    ],
    data = ["//system/molten/command"],
    env = {"MOLTEN_COMMAND": "$(rootpath //system/molten/command)"},
    deps = [
        "//system/molten",
        "@crate//:serde_json",
    ],
)
