load("//photonic:defs.bzl", "photonic_library")
load("//theorem:defs.bzl", "theorem")

theorem(
    name = "add",
    srcs = ["add.wave"],
    deps = [
        ":count",
        "//library/ternary:add",
        "//theorem:case",
    ],
)

theorem(
    name = "compare",
    srcs = ["compare.wave"],
    deps = [
        "//library/ternary:compare",
        "//library/ternary:subtract",
        "//theorem:case",
        "//theorem/ternary:role",
        "//theorem/ternary:unpack",
    ],
)

photonic_library(
    name = "count",
    srcs = ["count.particle"],
    deps = [
        "//library/ternary:successor",
        "//theorem/ternary:unpack",
    ],
)

theorem(
    name = "cycle",
    srcs = ["cycle.wave"],
    deps = [
        ":count",
        "//theorem:case",
    ],
)

theorem(
    name = "multiply",
    srcs = ["multiply.wave"],
    deps = [
        ":count",
        "//library/ternary:multiply",
        "//theorem:case",
    ],
)

theorem(
    name = "subtract",
    srcs = ["subtract.wave"],
    deps = [
        ":count",
        "//library/ternary:subtract",
        "//theorem:case",
        "//theorem/ternary:role",
    ],
)

theorem(
    name = "sum",
    srcs = ["sum.wave"],
    occurrence = 512,
    deps = [
        ":count",
        "//library/ternary:sum",
        "//theorem:case",
    ],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
