load("@bazel_skylib//rules:native_binary.bzl", "native_test")
load("@buildifier_prebuilt//:rules.bzl", "buildifier_test")
load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_test.bzl", "rust_test")
load(":node.bzl", "node")

buildifier_test(
    name = "check",
    size = "small",
    srcs = ["//:build"],
    lint_mode = "warn",
    mode = "check",
    tags = ["manual"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
        "node.bzl",
    ],
    visibility = ["//:__pkg__"],
)

node(
    name = "node",
    visibility = [
        "//browser:__pkg__",
        "//mathematics/ternary:__pkg__",
    ],
)

rust_binary(
    name = "execute",
    srcs = ["execute.rs"],
    crate_root = "execute.rs",
    visibility = [
        "//:__pkg__",
        "//browser:__pkg__",
        "//mathematics:__subpackages__",
    ],
    deps = ["@rules_rust//rust/runfiles"],
)

native_test(
    name = "browser",
    size = "small",
    src = ":execute",
    args = [
        "$(rlocationpath :node)",
        "$(rlocationpath browser.mjs)",
        "$(rlocationpath @rules_browsers_chrome_mac_arm//:chrome-headless-shell-mac-arm64/chrome-headless-shell)",
        "$(rlocationpath @rules_browsers_chromedriver_mac_arm//:chromedriver-mac-arm64/chromedriver)",
        "$(rlocationpath //browser:webassembly)",
        "$(rlocationpath //browser:javascript)",
    ],
    data = [
        "browser.mjs",
        ":node",
        "//:page",
        "//browser:javascript",
        "//browser:webassembly",
        "//document:source",
        "@rules_browsers_chrome_mac_arm//:chrome-headless-shell-mac-arm64/chrome-headless-shell",
        "@rules_browsers_chrome_mac_arm//:info",
        "@rules_browsers_chromedriver_mac_arm//:chromedriver-mac-arm64/chromedriver",
        "@rules_browsers_chromedriver_mac_arm//:info",
    ],
    tags = [
        "manual",
        "requires-network",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
)

rust_test(
    name = "runner",
    size = "small",
    srcs = ["test.rs"],
    crate_root = "test.rs",
    data = [
        "exit.mjs",
        ":execute",
        ":node",
    ],
    env = {
        "PHOTONIC_EXECUTE": "$(rlocationpath :execute)",
        "PHOTONIC_NODE": "$(rlocationpath :node)",
        "PHOTONIC_SCRIPT": "$(rlocationpath exit.mjs)",
    },
    deps = ["@rules_rust//rust/runfiles"],
)
