load("//photonic:defs.bzl", "photonic_binary", "photonic_test")

filegroup(
    name = "fixture",
    srcs = [
        "action.wave",
        "addition.wave",
        "archive.particle",
        "composition.wave",
        "membership.wave",
        "multiplication.wave",
        "product.wave",
        "result.particle",
        "retained.particle",
        "seven.particle",
        "six.particle",
        "successor.wave",
        "sum.wave",
        "ten.particle",
        "zero.particle",
    ],
    visibility = ["//language:__pkg__"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
    ],
    visibility = ["//:__pkg__"],
)

photonic_binary(
    name = "action",
    srcs = ["action.wave"],
)

photonic_binary(
    name = "addition",
    srcs = ["addition.wave"],
)

photonic_binary(
    name = "composition",
    srcs = ["composition.wave"],
)

photonic_binary(
    name = "membership",
    srcs = ["membership.wave"],
)

photonic_binary(
    name = "multiplication",
    srcs = ["multiplication.wave"],
)

photonic_binary(
    name = "product",
    srcs = ["product.wave"],
)

photonic_binary(
    name = "successor",
    srcs = ["successor.wave"],
)

photonic_binary(
    name = "sum",
    srcs = ["sum.wave"],
)

photonic_test(
    name = "successor.check",
    srcs = ["successor.wave"],
    source = "",
    targets = ["Unit.Unit.Unit"],
)

photonic_test(
    name = "membership.check",
    srcs = ["membership.wave"],
    source = "",
    targets = ["Natural"],
)

photonic_test(
    name = "addition.check",
    srcs = ["addition.wave"],
    source = "",
    targets = ["Unit.Unit.Unit.Unit.Unit"],
)

photonic_test(
    name = "sum.check",
    srcs = ["sum.wave"],
    source = "",
    targets = ["Unit.Unit.Unit.Unit.Unit.Unit.Unit.Unit.Unit.Unit"],
)

photonic_binary(
    name = "preparation",
    srcs = ["preparation.wave"],
)

photonic_test(
    name = "preparation.check",
    srcs = ["preparation.wave"],
    cells = 24,
    coherences = 8,
    frames = 30,
    source = "",
    states = 3000,
    steps = 100000,
    targets = ["Unit.Unit"],
)
