load("//theorem:defs.bzl", "theorem")

theorem(
    name = "converse",
    srcs = ["converse.wave"],
    every = True,
    deps = [
        "//theorem:case",
        "//theorem:judge",
    ],
)

theorem(
    name = "equality",
    srcs = ["equality.wave"],
    deps = [
        "//theorem:case",
        "//theorem:judge",
    ],
)

theorem(
    name = "transitive",
    srcs = ["transitive.wave"],
    configuration = 32768,
    every = True,
    deps = [
        "//theorem:case",
        "//theorem:judge",
    ],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
