load("//photonic:defs.bzl", "photonic_library")
load("//theorem:defs.bzl", "theorem")

photonic_library(
    name = "role",
    srcs = ["role.particle"],
    visibility = [
        "//theorem/counting:__pkg__",
        "//theorem/induction:__pkg__",
        "//theorem/natural:__pkg__",
    ],
)

theorem(
    name = "converse",
    srcs = ["converse.wave"],
    deps = [
        ":role",
        "//library/ternary:compare",
        "//library/ternary:equal",
        "//theorem:case",
        "//theorem:judge",
    ],
)

theorem(
    name = "field",
    srcs = ["field.wave"],
    occurrence = 512,
    deps = [
        ":unpack",
        "//library/boolean:and",
        "//library/boolean:or",
        "//library/ternary:add",
        "//library/ternary:equal",
        "//library/ternary:multiply",
        "//theorem:case",
    ],
)

theorem(
    name = "group",
    srcs = ["group.wave"],
    occurrence = 512,
    deps = [
        ":role",
        ":unpack",
        "//library/boolean:and",
        "//library/ternary:add",
        "//library/ternary:equal",
        "//library/ternary:subtract",
        "//theorem:case",
    ],
)

theorem(
    name = "order",
    srcs = ["order.wave"],
    occurrence = 512,
    deps = [
        ":role",
        "//library/ternary:compare",
        "//theorem:case",
        "//theorem:judge",
    ],
)

photonic_library(
    name = "unpack",
    srcs = ["unpack.particle"],
    visibility = [
        "//theorem/counting:__pkg__",
        "//theorem/induction:__pkg__",
        "//theorem/natural:__pkg__",
    ],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
