filegroup(
    name = "fixture",
    srcs = [
        "abstraction.wave",
        "addition.wave",
        "broadcast.wave",
        "concrete.particle",
        "crossed.particle",
        "double.particle",
        "extra.wave",
        "independent.wave",
        "isolated.wave",
        "natural.wave",
        "number.particle",
        "pair.wave",
        "selected.particle",
        "separate.particle",
        "shared.particle",
        "ten.particle",
    ],
    visibility = ["//system:__pkg__"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
    ],
    visibility = ["//:__pkg__"],
)
