load("//theorem:defs.bzl", "theorem")

theorem(
    name = "irreflexive",
    srcs = ["irreflexive.wave"],
    deps = ["//theorem:cover"],
)

theorem(
    name = "transitive",
    srcs = ["transitive.wave"],
    deps = ["//theorem:cover"],
)

theorem(
    name = "trichotomy",
    srcs = ["trichotomy.wave"],
    deps = ["//theorem:cover"],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
