load("//photonic:defs.bzl", "photonic_binary", "photonic_test")

filegroup(
    name = "fixture",
    srcs = [
        "addition.wave",
        "carry.particle",
        "product.particle",
        "result.particle",
    ],
    visibility = ["//language:__pkg__"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
    ],
    visibility = ["//:__pkg__"],
)

photonic_binary(
    name = "addition",
    srcs = ["addition.wave"],
)

photonic_test(
    name = "addition.check",
    srcs = ["addition.wave"],
    target = ["2^0.2^1.2^2.2^4.2^6.2^9.2^10"],
)
