filegroup(
    name = "source",
    srcs = [
        "book.css",
        "book.js",
        "evaluation.js",
        "graph.js",
        "native.js",
        "record.js",
        "reference.html",
        "style.css",
        "trace.js",
        "worker.js",
        "//document/kernel:source",
    ],
    visibility = ["//tool:__pkg__"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
        "//document/kernel:build",
    ],
    visibility = ["//:__pkg__"],
)
