filegroup(
    name = "source",
    srcs = [
        "arithmetic.json",
        "audit.json",
        "book.css",
        "book.js",
        "calculation.js",
        "demo.record.js",
        "evaluation.js",
        "execution.json",
        "expression.js",
        "expression.record.js",
        "graph.js",
        "inspection.js",
        "native.js",
        "numeral.js",
        "product.js",
        "record.js",
        "sandbox.js",
        "syntax.js",
        "worker.js",
    ],
    visibility = ["//toolchain/browser:__pkg__"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
    ],
    visibility = ["//:__pkg__"],
)

filegroup(
    name = "demo",
    srcs = ["demo.record.js"],
    visibility = ["//program/ternary:__pkg__"],
)

filegroup(
    name = "expression",
    srcs = ["expression.record.js"],
    visibility = ["//program/ternary:__pkg__"],
)

filegroup(
    name = "numeral",
    srcs = ["numeral.js"],
    visibility = [
        "//benchmark:__pkg__",
        "//toolchain/browser:__pkg__",
    ],
)
