load("//photonic:defs.bzl", "photonic_binary", "photonic_test")

photonic_binary(
    name = "rows",
    srcs = ["rows.wave"],
    deps = [
        "//library/natural:digit",
        "//library/vector:node",
        "//library/vector:reverse",
        "//library/vector:sort",
    ],
)

photonic_test(
    name = "rows.check",
    srcs = ["rows.wave"],
    coherence = 512,
    occurrence = 4096,
    path = True,
    record = 10000000,
    scope = 1024,
    target = ["Done"],
    work = 10000000,
    deps = [
        "//library/natural:digit",
        "//library/vector:node",
        "//library/vector:reverse",
        "//library/vector:sort",
    ],
)

photonic_binary(
    name = "sort",
    srcs = ["sort.wave"],
    deps = [
        "//library/natural:digit",
        "//library/vector:node",
        "//library/vector:sort",
    ],
)

photonic_test(
    name = "sort.check",
    srcs = ["sort.wave"],
    coherence = 512,
    occurrence = 4096,
    path = True,
    record = 10000000,
    scope = 1024,
    target = ["Done"],
    work = 10000000,
    deps = [
        "//library/natural:digit",
        "//library/vector:node",
        "//library/vector:sort",
    ],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
