'use strict';
window.program.example = (() => {
    const rule = (id,input,output) => ({id,input:input.split('.'),output:output.split('.')});
    const boolean = [rule('true','True','Boolean'),rule('false','False','Boolean')];
    const negate = [rule('negative','True','False'),rule('positive','False','True')];
    const example = (id,name,input,pattern,rule,body,question) => ({id,name,input:input.split('.'),pattern:pattern.split('.'),rule,body,question});
    const result = [
        {...example('direct','Direct negation','Not.True','Not.True',[],[],'Direct application subtracts Not.True and emits False, using the same residual law.'),output:['False']},
        example('negate','Derived negation','Not.True','Not.Boolean',boolean,negate,'An existing path to Not.Boolean enables an application at concrete Not.True. The body receives its remainder, True.'),
        example('false','Negating False','Not.False','Not.Boolean',boolean,negate,'Does the same rule mechanism give the symmetric result, without a built-in Boolean type?'),
        example('and','And with mixed operands','And.True.False.Extra','And.Boolean.Boolean',boolean,[rule('both','True.True','True'),rule('either','False','False')],'Should the unused True operand survive the operation? The uniform remainder law retains every unused operand.'),
        example('both','And with two True operands','And.True.True.Extra','And.Boolean.Boolean',boolean,[rule('both','True.True','True'),rule('either','False','False')],'Two equal labels have distinct origins. The derived pattern needs both.'),
        example('or','Or with mixed operands','Or.False.True.Extra','Or.Boolean.Boolean',boolean,[rule('either','True','True'),rule('neither','False.False','False')],'Outer context should survive; should an unused operand survive too?'),
        example('neither','Or with two False operands','Or.False.False','Or.Boolean.Boolean',boolean,[rule('either','True','True'),rule('neither','False.False','False')],'Repeated abstract requirements must bind different concrete origins.'),
        example('chain','Chained abstraction','Not.True.Extra','Not.Value',[...boolean,rule('value','Boolean','Value')],negate,'A longer path reaches Value through ordinary events. Does its nested body retain True and Extra?'),
        example('diamond','Two evidence routes, one source application','Not.True','Not.Boolean',[...boolean,rule('truth','True','Truth'),rule('boolean','Truth','Boolean')],negate,'Two routes to Boolean enable one inferred application at the same concrete source. Different incoming events remain visible on the shared evidence state.'),
        example('reuse','One operand cannot fill two slots','And.True','And.Boolean.Boolean',[...boolean,rule('truth','True','Truth'),rule('boolean','Truth','Boolean')],[rule('both','True.True','True')],'A single whole reachable view must cover Boolean.Boolean. Two alternative one-Boolean views cannot be pooled.'),
        example('permit','An abstraction needs two resources','Open.Card.Ticket.Extra','Open.Eligible',[rule('eligible','Card.Ticket','Eligible')],[rule('admit','Card.Ticket','Admitted')],'Eligibility depends on both Card and Ticket. Both concrete origins must be retained and validated.'),
        example('missing','Missing a supporting resource','Open.Card','Open.Eligible',[rule('eligible','Card.Ticket','Eligible')],[rule('admit','Card.Ticket','Admitted')],'No Ticket means no proof. Search must not create the missing resource.'),
        example('overlap','One resource supports two views','Use.Card.Ticket','Use.Eligible.Ticket',[rule('eligible','Card.Ticket','Eligible')],[rule('use','Card.Ticket','Used')],'Eligible already requires Ticket. Can that same Ticket also satisfy another consuming slot?'),
        example('cycle','Unsupported recursive abstraction','Not.True','Not.Boolean',[rule('value','Boolean','Value'),rule('boolean','Value','Boolean')],negate,'A cycle disconnected from concrete input cannot license an inferred application.'),
        example('ground','Supported recursive abstraction','Not.True','Not.Value',[...boolean,rule('value','Boolean','Value'),rule('boolean','Value','Boolean')],negate,'The cycle reuses existing states. New evidence can still enable applications at earlier concrete sources until the graph reaches a fixed point.'),
        example('ambiguous','Two alternative abstractions','Choose.Seed','Choose.Selectable',[rule('select','Seed','Selectable'),rule('warm','Seed','Warm'),rule('cool','Seed','Cool')],[rule('red','Warm','Red'),rule('blue','Cool','Blue')],'Two ordinary paths produce Red and Blue in alternative histories. Neither needs a special inference mode.'),
        example('shortcut','Unequal paths both progress','Choose.Seed','Choose.Selectable',[rule('select','Seed','Selectable'),rule('bridge','Seed','Bridge'),rule('warm','Bridge','Warm'),rule('cool','Seed','Cool')],[rule('red','Warm','Red'),rule('blue','Cool','Blue')],'One path is longer than another. Fair iteration should eventually expose both, with no shortest-proof dispatch.')
    ];
    const chain = Array.from({length:18},(_,index)=>rule('step'+index,index===0?'True':'Layer'+index,index===17?'Boolean':'Layer'+(index+1)));
    result.push(example('deep','A match after eighteen steps','Not.True','Not.Boolean',chain,negate,'The outer rule becomes enabled only after eighteen ordinary events. There is no type-depth cutoff.'));
    result.push(example('endless','A repeated state beside useful work','Not.True','Not.Boolean',[rule('loop','True','True'),...boolean],negate,'True → True is a self-loop on one state. It must not generate infinite duplicate work or hide the path to False.'));
    result.push(example('explicit','And with explicit operand handling','And.True.False.Extra','And.Boolean.Boolean',boolean,[rule('both','True.True','True'),rule('mixed','True.False','False'),rule('neither','False.False','False')],'The body explicitly removes both operands. There is no implicit disposal at return.'));
    result.push(example('double','Repeated negation','Not.Not.True','Not.Boolean',boolean,negate,'The first body produces Not.False. A later source-local application uses that False, not an earliest True ancestor.'));
    result.push(example('directbody','Direct nested rule consumes its operands','Not.True','Not.True',[],negate,'The directly matched Not and True are removed. The body receives an empty remainder and cannot negate it.'));
    result.push({...example('replacement','An inferred result replaces its concrete input','A.Extra','B',[rule('ab','A','B')],[],'B → C is enabled at concrete A.Extra by A → B. It consumes the bound A and preserves Extra: C.Extra, never A.C.Extra.'),output:['C']});
    result.push({...example('frame','Unrelated evidence work does not change leftovers','A.X','B',[rule('ab','A','B'),rule('xy','X','Y')],[],'A path through B.Y can justify B → C at A.X. Only the A belongs to the selected binding; its actual source leftover remains X.'),output:['C']});
    result.push({...example('flat','An inferred literal output consumes its witness','Not.True.Extra','Not.Boolean',boolean,[],'The literal False result replaces the bound Not.True. Extra survives; True is not appended as an extra result.'),output:['False']});
    return result;
})();
