load("//theorem:defs.bzl", "theorem")

theorem(
    name = "asymmetry",
    srcs = ["asymmetry.wave"],
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

theorem(
    name = "kernel",
    srcs = ["kernel.wave"],
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

theorem(
    name = "partition",
    srcs = ["partition.wave"],
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

theorem(
    name = "strict",
    srcs = ["strict.wave"],
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

theorem(
    name = "trichotomy",
    srcs = ["trichotomy.wave"],
    deps = [
        "//theorem:case",
        "//theorem:cover",
    ],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
