load("@rules_rs//rs:rust_binary.bzl", "rust_binary")

rust_binary(
    name = "record",
    srcs = ["record.rs"],
    compile_data = [
        "membership.wave",
        "natural.particle",
    ],
    crate_root = "record.rs",
    deps = [
        "//system:photonic",
        "@crate//:serde",
        "@crate//:serde_json",
    ],
)

filegroup(
    name = "fixture",
    srcs = [
        "action.wave",
        "addition.wave",
        "archive.particle",
        "composition.wave",
        "membership.wave",
        "multiplication.wave",
        "product.wave",
        "result.particle",
        "retained.wave",
        "seven.particle",
        "six.particle",
        "successor.wave",
        "sum.wave",
        "ten.particle",
        "zero.particle",
    ],
    visibility = ["//system:__pkg__"],
)

filegroup(
    name = "build",
    srcs = [
        "BUILD.bazel",
    ],
    visibility = ["//:__pkg__"],
)
