load("//theorem:defs.bzl", "theorem")

theorem(
    name = "annihilation.left",
    srcs = ["annihilation.left.wave"],
    path = False,
    deps = [],
)

theorem(
    name = "annihilation.right",
    srcs = ["annihilation.right.wave"],
    path = False,
    deps = [],
)

theorem(
    name = "negation",
    srcs = ["negation.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "sign",
    srcs = ["sign.wave"],
    every = True,
    path = False,
    deps = [],
)

theorem(
    name = "unit",
    srcs = ["unit.wave"],
    every = True,
    path = False,
    deps = [],
)

filegroup(
    name = "build",
    srcs = ["BUILD.bazel"],
    visibility = ["//:__pkg__"],
)
